#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Convert the MySQL dumps (forum.sql + badge_migration.sql) into an
H2-compatible bootstrap schema.

Output: bi-sheforum/forum/src/main/resources/db/schema-h2.sql
This file is executed by Spring Boot at startup when the `h2` profile is
active (spring.sql.init), so the app runs standalone with an embedded
database and needs no MySQL server.

Safe to run repeatedly: DROP TABLE IF EXISTS keeps it idempotent.

Usage:  python tools/migrate_sql.py
"""
import re
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = [
    os.path.join(BASE, "bi-sheforum", "forum.sql"),
    os.path.join(BASE, "bi-sheforum", "forum", "src", "main", "resources", "badge_migration.sql"),
]
OUT = os.path.join(BASE, "bi-sheforum", "forum", "src", "main", "resources", "db", "schema-h2.sql")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def protect_backticks(line: str):
    """Replace `...` identifiers with placeholders so type rewrites never
    touch a column named like a SQL type (e.g. `text`)."""
    parts = []

    def repl(m):
        parts.append(m.group(0))
        return "\x00%d\x00" % (len(parts) - 1)

    protected = re.sub(r"`[^`]*`", repl, line)
    return protected, parts


def restore(line: str, parts) -> str:
    for i, p in enumerate(parts):
        line = line.replace("\x00%d\x00" % i, p)
    return line


# Column-level / DDL-level rewrites applied inside and outside CREATE TABLE.
TYPE_REWRITES = [
    (re.compile(r"\bINT\(\d+\)\b", re.I), "INT"),
    (re.compile(r"\bBIGINT\(\d+\)\b", re.I), "BIGINT"),
    (re.compile(r"\bTINYINT\(\d+\)\b", re.I), "TINYINT"),
    (re.compile(r"\bDOUBLE\s*\(\s*\d+\s*,\s*\d+\s*\)", re.I), "DOUBLE"),
    (re.compile(r"\bDECIMAL\s*\(\s*\d+\s*,\s*\d+\s*\)", re.I), "DECIMAL"),
    (re.compile(r"\bDATETIME\b", re.I), "TIMESTAMP"),
    (re.compile(r"\bTEXT\b", re.I), "CLOB"),
    (re.compile(r"\bUNSIGNED\s+ZEROFILL\b", re.I), ""),
    (re.compile(r"\bUNSIGNED\b", re.I), ""),
    (re.compile(r"\bCHARACTER\s+SET\s+\w+(?:\s+COLLATE\s+\w+)?", re.I), ""),
    (re.compile(r"\bCOLLATE\s+\w+", re.I), ""),
    (re.compile(r"\bUSING\s+BTREE\b", re.I), ""),
    (re.compile(r"COMMENT\s+'[^']*'", re.I), ""),
]


def should_drop_row(line: str) -> bool:
    """Return True when a row should be removed entirely."""
    if re.match(r"^SET\s+(NAMES|FOREIGN_KEY_CHECKS|sql_mode|@|autocommit|GLOBAL|SESSION)", line, re.I):
        return True
    if re.match(r"^USE\s+", line, re.I):
        return True
    if re.match(r"^(DROP|CREATE)\s+(PROCEDURE|FUNCTION|TRIGGER|EVENT)\b", line, re.I):
        return True
    if line.strip().upper().startswith("DELIMITER"):
        return True
    # Secondary indexes are dropped (small data volume, avoids schema-level
    # index-name clashes in H2). UNIQUE KEY (converted to a constraint later)
    # and PRIMARY KEY are kept.
    if re.match(r"^\s*UNIQUE\s+KEY\s+[\w`]+\s*\(", line, re.I):
        return False
    if "PRIMARY" not in line.upper() and re.match(
        r"^\s*((KEY|INDEX)\s+[\w`]+\s*\()", line, re.I
    ):
        return True
    return False


def transform_row(line: str) -> str:
    for pat, repl in TYPE_REWRITES:
        line = pat.sub(repl, line)
    line = re.sub(r"\bAFTER\s+[\w`]+", "", line, flags=re.I)
    line = re.sub(r"\bVALUE\s*\(", "VALUES (", line, flags=re.I)
    return line.rstrip()


def transform_ddl(line: str, in_create: bool) -> str:
    line = transform_row(line)
    if not in_create:
        return line
    # UNIQUE KEY uk_x (a, b)  ->  CONSTRAINT uk_x UNIQUE (a, b)
    m = re.match(r"^\s*UNIQUE\s+KEY\s+([\w`]+)\s*\(([^)]+)\)\s*,?\s*$", line, re.I)
    if m:
        return "  CONSTRAINT %s UNIQUE (%s)" % (m.group(1), m.group(2))
    # strip MySQL ENGINE = INNODB ... AUTO_INCREMENT = N ... trailer
    line = re.sub(r"\s*ENGINE\s*=.*?;\s*$", ";", line, flags=re.I)
    return line


def convert(source_paths, out_path):
    out = [
        "-- ===================================================================",
        "-- H2 bootstrap schema (auto-generated by tools/migrate_sql.py)",
        "--",
        "-- MySQL forum.sql + badge_migration.sql -> H2 compatible DDL + seed data.",
        "-- Executed automatically by Spring Boot with profile `h2`.",
        "-- Idempotent: tables are dropped and re-created on every startup.",
        "-- Do not edit manually; edit the MySQL sources and re-run the script.",
        "-- ===================================================================",
    ]
    for src in source_paths:
        if not os.path.exists(src):
            print("[WARN] missing source:", src)
            continue
        print("[*] converting", src)
        text = open(src, encoding="utf-8", errors="replace").read()
        in_block_comment = False
        in_proc = False
        in_create = False
        alter_table = None
        for raw in text.splitlines():
            s = raw.strip()
            if in_block_comment:
                if "*/" in s:
                    in_block_comment = False
                continue
            if s.startswith("/*"):
                if "*/" not in s:
                    in_block_comment = True
                continue
            if in_proc:
                if s.upper().startswith("DELIMITER ;"):
                    in_proc = False
                continue
            if s.upper().startswith("DELIMITER") or re.match(
                r"^(DROP|CREATE)\s+(PROCEDURE|FUNCTION|TRIGGER|EVENT)\b", s, re.I
            ):
                in_proc = True
                continue
            if should_drop_row(raw):
                continue
            protected, parts = protect_backticks(raw)
            # Split multi-column ALTER TABLE ... ADD COLUMN into single statements
            if re.match(r"^\s*ALTER\s+TABLE\b", s, re.I):
                m = re.match(r"^\s*ALTER\s+TABLE\s+([\w`]+)\s*$", protected, re.I)
                alter_table = restore(m.group(1), parts) if m else None
                out.append("")
                continue
            if alter_table and re.match(r"^\s*ADD\s+COLUMN\b", s, re.I):
                col = re.sub(r"^\s*ADD\s+COLUMN\s*", "", protected, flags=re.I).strip()
                col = transform_row(col).rstrip(",").rstrip()
                col = restore(col, parts)
                out.append("ALTER TABLE %s ADD COLUMN %s;" % (alter_table, col))
                continue
            row = transform_ddl(protected, in_create)
            row = restore(row, parts)
            if re.match(r"^\s*CREATE\s+TABLE\b", s, re.I):
                # 迁移表/徽章表用 IF NOT EXISTS，二次启动不会重建导致重复插入；
                # 统一改为 DROP + CREATE，保证每次启动幂等重建。
                if re.match(r"^\s*CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\b", s, re.I):
                    m = re.match(r"^\s*CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+([\w`]+)", s, re.I)
                    out.append("DROP TABLE IF EXISTS %s;" % restore(m.group(1), parts))
                    row = re.sub(r"\s*IF\s+NOT\s+EXISTS", "", row, flags=re.I, count=1)
                in_create = True
            elif in_create and s.startswith(")"):
                # remove the trailing comma left behind by a dropped index row
                for i in range(len(out) - 1, -1, -1):
                    if out[i].strip():
                        if out[i].rstrip().endswith(","):
                            out[i] = out[i].rstrip()[:-1]
                        break
                in_create = False
            out.append(row)
        out.append("")
    out.append("")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("[*] wrote", out_path)


if __name__ == "__main__":
    convert(SOURCES, OUT)
